import "./App.css";
import "./lib/styles.css";
import { useContext } from "react";
import { STRLContext } from "./lib/Context";

function App() {
  const courseData = {
    categoryName: "Career",
    categoryId: 5,
    categoryImg: "",
    courseId: 33,
    shortName: "Work Readiness",
    displayName: "Work Readiness",
    description: "Work Readiness",
    courseImg:
      "https://lms.skillstrainer.in/moodle/pluginfile.php/23901/course/overviewfiles/JOB%20Readiness.png",
    students_enrolled: "22,780",
    digitalContentDuration: "3",
    nsqf_lvl: null,
    redirection_url:
      "https://lms.skillstrainer.in/moodle/course/view.php?id=58",
    cost: 999,
    discount: null,
    modules: [
      {
        id: 648,
        name: "General",
        visible: 1,
        summary: "",
        summaryformat: 1,
        section: 0,
        hiddenbynumsections: 0,
        uservisible: true,
        modules: [
          {
            id: 1998,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=1998",
            name: "Pre-Assessment",
            instance: 1882,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1638945448,
              overrideby: null,
              valueused: false,
            },
          },
        ],
      },
      {
        id: 653,
        name: "Module 1: Welcome and Introduction to the Program",
        visible: 1,
        summary: "",
        summaryformat: 1,
        section: 1,
        hiddenbynumsections: 0,
        uservisible: true,
        modules: [
          {
            id: 708,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=708",
            name: "Unit 1.1 Welcome &amp;  Introduction to the  Job Readiness Program",
            instance: 658,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1587632334,
              overrideby: null,
              valueused: false,
            },
          },
        ],
      },
      {
        id: 649,
        name: "Module 2: Softskills and Professional Skills",
        visible: 1,
        summary: "",
        summaryformat: 1,
        section: 2,
        hiddenbynumsections: 0,
        uservisible: true,
        modules: [
          {
            id: 651,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=651",
            name: "Unit 2.1 Communication Skills",
            instance: 601,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1622530848,
              overrideby: null,
              valueused: false,
            },
          },
          {
            id: 652,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=652",
            name: "Unit 2.2: Team Work",
            instance: 602,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1564486563,
              overrideby: null,
              valueused: false,
            },
          },
          {
            id: 679,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=679",
            name: "Unit 2.3: Interpersonal Skills",
            instance: 629,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1591354886,
              overrideby: null,
              valueused: false,
            },
          },
          {
            id: 680,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=680",
            name: "Unit 2.4: Time Management &amp; Goal Setting",
            instance: 630,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1634024797,
              overrideby: null,
              valueused: false,
            },
          },
          {
            id: 699,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=699",
            name: "Unit 2.5: Problem Solving &amp; Decision Making",
            instance: 649,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 0,
              timecompleted: 0,
              overrideby: null,
              valueused: false,
            },
          },
          {
            id: 700,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=700",
            name: "Unit 2.6: Commitment to Continues Self Growth",
            instance: 650,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1568377605,
              overrideby: null,
              valueused: false,
            },
          },
          {
            id: 701,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=701",
            name: "Unit 2.7: Leadership Skills",
            instance: 651,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1638956270,
              overrideby: null,
              valueused: false,
            },
          },
          {
            id: 702,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=702",
            name: "Unit 2.8: Important Life Values",
            instance: 652,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1568879951,
              overrideby: null,
              valueused: false,
            },
          },
          {
            id: 710,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=710",
            name: "Unit 2.9: Our Duties &amp; Responsibilities",
            instance: 659,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 0,
              timecompleted: 0,
              overrideby: null,
              valueused: false,
            },
          },
        ],
      },
      {
        id: 650,
        name: "Module 3: Basic Language Skills",
        visible: 1,
        summary: "",
        summaryformat: 1,
        section: 3,
        hiddenbynumsections: 0,
        uservisible: true,
        modules: [
          {
            id: 698,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=698",
            name: "Unit 3.1: Language Skills",
            instance: 648,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 0,
              timecompleted: 0,
              overrideby: null,
              valueused: false,
            },
          },
        ],
      },
      {
        id: 651,
        name: "Module 4: Personal Health, Hygeine and Grooming",
        visible: 1,
        summary: "",
        summaryformat: 1,
        section: 4,
        hiddenbynumsections: 0,
        uservisible: true,
        modules: [
          {
            id: 697,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=697",
            name: "Unit 4.1: Personal Grooming,  Health and Hygiene",
            instance: 647,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1638161684,
              overrideby: null,
              valueused: false,
            },
          },
        ],
      },
      {
        id: 652,
        name: "Module 5: Interview Skills",
        visible: 1,
        summary: "",
        summaryformat: 1,
        section: 5,
        hiddenbynumsections: 0,
        uservisible: true,
        modules: [
          {
            id: 650,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=650",
            name: "Unit 5.1: Resume Writing, Interview Skills and Group Discuss",
            instance: 600,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 0,
              timecompleted: 0,
              overrideby: null,
              valueused: false,
            },
          },
        ],
      },
      {
        id: 763,
        name: "Final Assessments",
        visible: 1,
        summary: "<p>All questions are mandatory.&nbsp;</p>",
        summaryformat: 1,
        section: 6,
        hiddenbynumsections: 0,
        uservisible: true,
        modules: [
          {
            id: 2000,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=2000",
            name: "Final Assessment - 1",
            instance: 1884,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1635444856,
              overrideby: null,
              valueused: false,
            },
          },
          {
            id: 804,
            url: "https://lms.skillstrainer.in/moodle/mod/scorm/view.php?id=804",
            name: "Final Assessment - 2",
            instance: 748,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/scorm/1653284658/icon",
            modname: "scorm",
            modplural: "SCORM packages",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata:
              '{"customcompletionrules":{"completionstatusrequired":null,"completionscorerequired":null,"completionstatusallscos":"0"}}',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1634026120,
              overrideby: null,
              valueused: false,
            },
          },
          {
            id: 1049,
            url: "https://lms.skillstrainer.in/moodle/mod/customcert/view.php?id=1049",
            name: "Certificate",
            instance: 14,
            visible: 1,
            uservisible: true,
            visibleoncoursepage: 1,
            modicon:
              "https://lms.skillstrainer.in/moodle/theme/image.php/adaptable/customcert/1653284658/icon",
            modname: "customcert",
            modplural: "Custom certificates",
            availability: null,
            indent: 0,
            onclick: "",
            afterlink: null,
            customdata: '""',
            noviewlink: false,
            completion: 2,
            completiondata: {
              state: 1,
              timecompleted: 1629895517,
              overrideby: null,
              valueused: false,
            },
          },
        ],
      },
    ],
    partners: [],
  };

  const {
    multiLang: { publishMarketingWebsite },
  } = useContext(STRLContext);

  return (
    <div className="grid grid-cols-5 m-5">
      <button onClick={publishMarketingWebsite}>Click me</button>
    </div>
  );
}

export default App;
